/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funcionestaller2;

/**
 *
 * @author jekadrian
 */

public class Votaciones extends javax.swing.JDialog {

    private int nulos;
    private int blancos;
    

    /**
     * Creates new form Votaciones
     */
    public Votaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jlaTitulo = new javax.swing.JLabel();
        jlaNumVotos = new javax.swing.JLabel();
        jteNumVotos = new javax.swing.JTextField();
        jpaRegistrarVoto = new javax.swing.JPanel();
        jlaConVotos = new javax.swing.JLabel();
        jteConVotos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jteIngVotos = new javax.swing.JTextField();
        jlaLeyenda = new javax.swing.JLabel();
        jlaLeyenda1 = new javax.swing.JLabel();
        jbuRegistrarVotos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jlaMoreno = new javax.swing.JLabel();
        jteMoreno = new javax.swing.JTextField();
        jlaLasso = new javax.swing.JLabel();
        jteLasso = new javax.swing.JTextField();
        jlaNulos = new javax.swing.JLabel();
        jteNulos = new javax.swing.JTextField();
        jlaBlancos = new javax.swing.JLabel();
        jteBlancos = new javax.swing.JTextField();
        Lassox100 = new javax.swing.JTextField();
        Morenox100 = new javax.swing.JTextField();
        Blancosx100 = new javax.swing.JTextField();
        Nulosx100 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLaEstadoVotaciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlaTitulo.setText("Votaciones Ecuador 2017");
        getContentPane().add(jlaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 11, -1, -1));

        jlaNumVotos.setText("Ingrese el numero de votos:");
        getContentPane().add(jlaNumVotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, -1, -1));

        jteNumVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jteNumVotosActionPerformed(evt);
            }
        });
        getContentPane().add(jteNumVotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 44, 35, -1));

        jpaRegistrarVoto.setBorder(new javax.swing.border.MatteBorder(null));
        jpaRegistrarVoto.setForeground(java.awt.Color.lightGray);
        jpaRegistrarVoto.setMaximumSize(new java.awt.Dimension(32767, 900));

        jlaConVotos.setText("Contador de Votos");

        jteConVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jteConVotosActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese el # del candidato elegido:");

        jteIngVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jteIngVotosActionPerformed(evt);
            }
        });

        jlaLeyenda.setText("Ingrese # 1 para votar por Moreno   Ingrese #2 para votar por Lennin");

        jlaLeyenda1.setText("Ingrese # 3 para votar en blanco      Ingrese #4 para votar Nulo");

        jbuRegistrarVotos.setText("Registrar Voto Elegido");
        jbuRegistrarVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuRegistrarVotosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaRegistrarVotoLayout = new javax.swing.GroupLayout(jpaRegistrarVoto);
        jpaRegistrarVoto.setLayout(jpaRegistrarVotoLayout);
        jpaRegistrarVotoLayout.setHorizontalGroup(
            jpaRegistrarVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaRegistrarVotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaRegistrarVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaRegistrarVotoLayout.createSequentialGroup()
                        .addGroup(jpaRegistrarVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlaLeyenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlaLeyenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlaConVotos)
                            .addGroup(jpaRegistrarVotoLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jteConVotos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(202, 202, 202))
                    .addGroup(jpaRegistrarVotoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jteIngVotos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jpaRegistrarVotoLayout.createSequentialGroup()
                .addComponent(jbuRegistrarVotos)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpaRegistrarVotoLayout.setVerticalGroup(
            jpaRegistrarVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaRegistrarVotoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jpaRegistrarVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlaConVotos)
                    .addComponent(jteConVotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlaLeyenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlaLeyenda1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpaRegistrarVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jteIngVotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbuRegistrarVotos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpaRegistrarVoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 160));

        jButton1.setText("Enviar # de votos a registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 43, -1, -1));

        jlaMoreno.setText("Votos Totales por  Moreno:");
        getContentPane().add(jlaMoreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jteMoreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jteMorenoActionPerformed(evt);
            }
        });
        getContentPane().add(jteMoreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 52, -1));

        jlaLasso.setText("Votos Totales por Lasso:");
        getContentPane().add(jlaLasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jteLasso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jteLassoActionPerformed(evt);
            }
        });
        getContentPane().add(jteLasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 52, -1));

        jlaNulos.setText("Votos Totales Nulos:");
        getContentPane().add(jlaNulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));
        getContentPane().add(jteNulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 52, -1));

        jlaBlancos.setText("Votos Totales en Blancos:");
        getContentPane().add(jlaBlancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jteBlancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jteBlancosActionPerformed(evt);
            }
        });
        getContentPane().add(jteBlancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 52, -1));
        getContentPane().add(Lassox100, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 34, -1));

        Morenox100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Morenox100ActionPerformed(evt);
            }
        });
        getContentPane().add(Morenox100, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 34, -1));
        getContentPane().add(Blancosx100, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 34, -1));
        getContentPane().add(Nulosx100, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 34, -1));

        jLabel2.setText("%");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jLabel3.setText("%");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jLabel4.setText("%");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        jLabel5.setText("%");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        jLabel6.setText("Igual a");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel7.setText("Igual a");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel8.setText("Igual a");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel9.setText("Igual a");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jLaEstadoVotaciones.setText("Estado Votaciones:");
        getContentPane().add(jLaEstadoVotaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jteConVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jteConVotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jteConVotosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.numeroVotos= Integer.parseInt( this.jteNumVotos.getText());
        this.jteConVotos.setText("0");
        this.moreno=0;
        this.lasso=0; 
        this.blancos=0;
        this.nulos=0;              
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbuRegistrarVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuRegistrarVotosActionPerformed
        // TODO add your handling code here:
        int voto=0;        
        voto= Integer.parseInt(this.jteIngVotos.getText());
        int contadorVoto=Integer.parseInt(this.jteConVotos.getText());
         
        if (contadorVoto<this.numeroVotos) {
            contadorVoto++;        
             if(voto==1){
            this.moreno=this.moreno+1;
            }
            if(voto==2){
            this.lasso=this.lasso+1;
            }
            if(voto==3){
            this.blancos=this.blancos+1;
            }
            if(voto==4){
            this.nulos=this.nulos+1;
            }
        }
        else{
             this.jLaEstadoVotaciones  .setText("Estadode Votaciones: Error Hallegado al# maximo de de registro Votos");
        }
        int moreno=(this.moreno*100)/this.numeroVotos;
        int lasso=(this.lasso*100)/this.numeroVotos;
        int blancos=(this.blancos*100)/this.numeroVotos;
        int nulos=(this.nulos*100)/this.numeroVotos;
        this.jteConVotos.setText(String.valueOf(contadorVoto));
        this.jteMoreno.setText(String.valueOf(this.moreno));
        this.jteLasso.setText(String.valueOf(this.lasso));
        this.jteBlancos.setText(String.valueOf(this.blancos));
        this.jteNulos.setText(String.valueOf(this.nulos));
        this.Morenox100.setText(String.valueOf(moreno));
        this.Lassox100.setText(String.valueOf(lasso));
        this.Blancosx100.setText(String.valueOf(blancos));
        this.Nulosx100.setText(String.valueOf(nulos));
    }//GEN-LAST:event_jbuRegistrarVotosActionPerformed

    private void jteLassoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jteLassoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jteLassoActionPerformed

    private void jteBlancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jteBlancosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jteBlancosActionPerformed

    private void jteIngVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jteIngVotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jteIngVotosActionPerformed

    private void jteNumVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jteNumVotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jteNumVotosActionPerformed

    private void jteMorenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jteMorenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jteMorenoActionPerformed

    private void Morenox100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Morenox100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Morenox100ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Votaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Votaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Votaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Votaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Votaciones dialog = new Votaciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private int lasso = 0;

    /**
     * Get the value of lasso
     *
     * @return the value of lasso
     */
    public int getLasso() {
        return lasso;
    }

    /**
     * Set the value of lasso
     *
     * @param lasso new value of lasso
     */
    public void setLasso(int lasso) {
        this.lasso = lasso;
    }

    private int moreno = 0;

    /**
     * Get the value of moreno
     *
     * @return the value of moreno
     */
    public int getMoreno() {
        return moreno;
    }

    /**
     * Set the value of moreno
     *
     * @param moreno new value of moreno
     */
    public void setMoreno(int moreno) {
        this.moreno = moreno;
    }

    private int numeroVotos = 0;

    /**
     * Get the value of numeroVotos
     *
     * @return the value of numeroVotos
     */
    public int getNumeroVotos() {
        return numeroVotos;
    }

    /**
     * Set the value of numeroVotos
     *
     * @param numeroVotos new value of numeroVotos
     */
    public void setNumeroVotos(int numeroVotos) {
        this.numeroVotos = numeroVotos;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Blancosx100;
    private javax.swing.JTextField Lassox100;
    private javax.swing.JTextField Morenox100;
    private javax.swing.JTextField Nulosx100;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLaEstadoVotaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton jbuRegistrarVotos;
    private javax.swing.JLabel jlaBlancos;
    private javax.swing.JLabel jlaConVotos;
    private javax.swing.JLabel jlaLasso;
    private javax.swing.JLabel jlaLeyenda;
    private javax.swing.JLabel jlaLeyenda1;
    private javax.swing.JLabel jlaMoreno;
    private javax.swing.JLabel jlaNulos;
    private javax.swing.JLabel jlaNumVotos;
    private javax.swing.JLabel jlaTitulo;
    private javax.swing.JPanel jpaRegistrarVoto;
    private javax.swing.JTextField jteBlancos;
    private javax.swing.JTextField jteConVotos;
    private javax.swing.JTextField jteIngVotos;
    private javax.swing.JTextField jteLasso;
    private javax.swing.JTextField jteMoreno;
    private javax.swing.JTextField jteNulos;
    private javax.swing.JTextField jteNumVotos;
    // End of variables declaration//GEN-END:variables
}
